### ISSUE TITLE
Doesn't see any gradients

### ISSUE THREAD

**Issue by scorp84** [webkul/coolhue#6]
And Sketch crashes. Sketch newest version. Midnight Plugin. Mojava with Dark Mode

**Comment by webkul-nitish** [comment]
That sounds weird 😞 . We will look into it. Can you just let us know the exact Sketch Version and a Snapshot of the CoolHue Plugin where it doesn't show any gradients.

**Comment by scorp84** [comment]
![bildschirmfoto 2018-12-11 um 14 21 44](https://user-images.githubusercontent.com/1840264/49803452-297bf280-fd50-11e8-8fb8-507970a05e20.png)
![bildschirmfoto 2018-12-11 um 14 21 54](https://user-images.githubusercontent.com/1840264/49803453-297bf280-fd50-11e8-980a-5e66f3b5fe77.png)

**Comment by webkul-nitish** [comment]
Can you just confirm one more small thing that your Internet Connection is in working mode. That may be one of the glitches as CoolHue fetches Gradients in real time and then caches them.

**Comment by scorp84** [comment]
Yeah. Internet is there.

**Comment by webkul-nitish** [comment]
@scorp84 Thanks for being so responsive. I have just addressed the bug and It has been fixed in the latest release. Update CoolHue Plugin right from SketchApp or [Download](https://github.com/webkul/coolhue/releases/download/v2.0.4/CoolHue.sketchplugin.zip) from release section.

Would really be glad to hear back from you and if you ❤️ CoolHue 🐦 Tweet a bit ✌️✌️

**Comment by patmien** [comment]
Hello all, I thought this issue has bee resolved but I am still having the same issue, no gradients are shown and the CoolHue opens with a empty window. I am running CoolHue 2.0.7 and Sketch 64. OS is macOS Catalina. See attached Screenshot.
<img width="252" alt="Screen Shot 2020-04-27 at 9 58 43 PM" src="https://user-images.githubusercontent.com/40737274/80438475-4926a300-88d2-11ea-99fc-8ec5303d4f2b.png">
